### ISSUE TITLE
RSS feed links are broken

### ISSUE THREAD

**Issue by shreyasminocha** [Smittyvb/smitop.com#1]
For example for the 'Using Colemak for a year' entry, my feed reader tries to open `https://post/colemak-year/` because the `link` tag within the corresponding `item` in [`index.xml`](https://smitop.com/index.xml) is `/post/colemak-year/`. I'm pretty sure this is because of:

https://github.com/Smittyvb/smitop.com/blob/a91b669c1da716df9e33139a1120a612c78f5e50/config.toml#L1

Changing `"/"` to `"https://smitop.com/"` should fix it.

**Comment by syvb** [comment]
Thanks! Fixed in a962912de3485ce001e384fc8274e563bd696917.
